# OpenWeatherMap configuration
[openweathermap]
enabled = true
api_key = "file:/home/sven/keys/openweather_apikey"
city_id = "4229476"
notification_timeout = 10 # 10 seconds
notification_body = "Expected within the next 3 hours"
sync_frequency = 600 # 10 minutes
# Output format, using Handlebars syntax, meaning variables should be used like {{ this }}
# Available tokens are:
# - temp_celsius
# - temp_kelvin
# - temp_fahrenheit
# - temp_icon
# - trend
# - forecast_celsius
# - forecast_kelvin
# - forecast_fahrenheit
# - forecast_icon
display = "{{ temp_icon }} {{ temp_fahrenheit }}°F {{ trend }} {{forecast_icon}} {{forecast_fahrenheit}}"

# GitHub configuration
[github]
enabled = false
api_key = "file:~/.config/ntfd/github.txt"
notification_timeout = 20 # 20 seconds
show_avatar = true
sync_frequency = 30 # 30 seconds
# Output format, using Handlebars syntax, meaning variables should be used like {{ this }}
# Available tokens are:
# - unread_count
# - first_time_count
display = " {{ unread_count }}"

# MPD configuration
[mpd]
enabled = false
# Top level directory containing your MPD collection
# Should be the same value as "music_directory" from your mpd.conf
music_directory = "/mnt/media/music"
notification_timeout = 10 # 10 seconds
# Cover art files should have standardized names and formats within your collection
# Specify the file name we should look for here
cover_name = "cover.jpg"
# When this is enabled, songs with missing cover image will not trigger a notification
skip_missing_cover = true
