vim.o.guifont = "FantasqueSansM Nerd Font:h12"
vim.g.neovide_scroll_animation_length = 0.5
vim.g.neovide_refresh_rate = 60
vim.g.idle_refresh_rate = 5
vim.g.neovide_confirm_quit = false
vim.g.neovide_cursor_animation_length = 0.01
vim.g.neovide_cursor_trail_size = 0.5
vim.g.neovide_cursor_antialiasing = false
vim.g.neovide_cursor_animate_in_insert_mode = true
vim.g.neovide_cursor_animate_command_line = true
vim.g.neovide_cursor_vfx_mode = "pixiedust"
vim.g.neovide_cursor_vfx_opacity = 500.0
vim.g.neovide_cursor_vfx_particle_lifetime = 1.2
vim.g.neovide_cursor_vfx_particle_density = 10.0
vim.g.neovide_cursor_vfx_particle_speed = 5.0
