[buildPlans.dead-sevka]
family = "DeadSevka"
spacing = "normal"
serifs = "sans"
no-cv-ss = true

[buildPlans.dead-sevka.variants.design]
capital-a = "curly-top-serifed"
capital-b = "more-asymmetric-interrupted-unilateral-serifed"
capital-c = "unilateral-serifed"
capital-d = "standard-unilateral-serifed"
capital-e = "top-left-serifed"
capital-f = "top-left-serifed"
capital-g = "toothless-corner-serifed-hooked"
capital-h = "top-left-bottom-right-serifed"
capital-i = "serifless"
capital-j = "descending-serifed"
capital-k = "curly-top-left-and-bottom-right-serifed"
capital-l = "motion-serifed"
capital-m = "hanging-motion-serifed"
capital-n = "asymmetric-motion-serifed"
capital-p = "open-motion-serifed"
capital-q = "open-swash"
capital-r = "standing-open-motion-serifed"
capital-s = "unilateral-inward-serifed"
capital-t = "motion-serifed"
capital-u = "toothless-corner-unilateral-motion-serifed"
capital-v = "curly-motion-serifed"
capital-w = "straight-vertical-sides-motion-serifed"
capital-x = "curly-motion-serifed"
capital-y = "curly-motion-serifed"
capital-z = "curly-top-serifed-with-crossbar"
a = "single-storey-earless-corner-tailed"
b = "toothless-corner-motion-serifed"
c = "unilateral-inward-serifed"
d = "toothless-corner-serifless"
e = "rounded"
f = "flat-hook-diagonal-tailed-crossbar-at-x-height"
g = "double-storey-open"
h = "straight-top-left-serifed"
i = "serifed-diagonal-tailed"
j = "diagonal-tailed-serifed"
k = "diagonal-tailed-cursive-top-left-serifed"
l = "serifed-diagonal-tailed"
m = "short-leg-top-left-serifed"
n = "earless-corner-tailed"
p = "earless-corner"
q = "earless-corner-diagonal-tailed"
r = "corner-hooked"
s = "unilateral-inward-serifed"
t = "diagonal-tailed"
u = "toothless-corner-motion-serifed"
v = "straight-motion-serifed"
w = "curly-motion-serifed"
x = "straight-motion-serifed"
y = "straight-turn-motion-serifed"
z = "curly-serifless-with-crossbar"
long-s = "bent-hook-tailed"
eszet = "sulzbacher-descending"
turn-v = "curly"
lower-delta = "flat-top"
capital-gamma = "serifed"
lower-iota = "serifed-flat-tailed"
lower-lambda = "curly-turn"
cyrl-ef = "top-serifed"
cyrl-che = "tailed"
cyrl-capital-u = "straight"
cyrl-capital-ya = "curly-open"
cyrl-ya = "curly-open-tailed"
zero = "slashed-split"
one = "no-base-flat-top-serif"
three = "flat-top"
four = "semi-open-non-crossing"
asterisk = "penta-low"
caret = "low"
paren = "large-contour"
brace = "curly"
number-sign = "upright-open"
ampersand = "flat-top"
at = "fourfold-tall"
dollar = "interrupted-cap"
cent = "bar-interrupted"
percent = "rings-continuous-slash-also-connected"
lig-ltgteq = "slanted"
ascii-single-quote = "raised-comma"
question = "corner-flat-hooked"
punctuation-dot = "square"
