#!/bin/bash

scan="/tmp/scan"
touch $scan
# sudo arp-scan --interface=wlp3s0 --localnet -g > $scan
sudo nmap -sP 192.168.50.0/24 > $scan

# number=`grep -c "locally administered" $scan`
number=`grep -c "Unknown" $scan`
echo $number
# echo "something"

rm /tmp/scan
