"$schema" = 'https://starship.rs/config-schema.json'

format = """
$username\
$directory\
$git_branch\
$git_status\
$fill\
$c\
$elixir\
$elm\
$golang\
$haskell\
$java\
$julia\
$nim\
$rust\
$scala\
$conda\
$python\
$time\n\
\\$ 
"""

palette = "modus-operandi"

[palettes.modus-operandi]
overlay = '#ffffff'
red = '#a60000'
yellow = '#6f5500'
pink = '#7b435c'
aqua = '#0031a9'
cyan = '#005e8b'
purple = '#4a3a8a'
nord_bg = '#2e3440'
nord_fg = '#d8dee9'

[directory]
format = "\\[$path\\]"
style = "bg:none fg:aqua"
truncation_length = 0
truncate_to_repo = true
# truncation_symbol = "…/"

[directory.substitutions]
Documents = "󰈙"
Downloads = " "
Music = " "
Pictures = " "

[fill]
style = "fg:overlay"
symbol = " "

[git_branch]
# format = "[](fg:overlay)[ $symbol $branch ]($style)[](fg:overlay) "
format = "\\[[$branch]($style)"
style = "bg:none fg:cyan"
symbol = ""

[git_status]
disabled = false
style = "bg:none fg:red"
# format = '[](fg:none)([$all_status$ahead_behind]($style))[](fg:none) '
format = ' $all_status$ahead_behind\]'
up_to_date = '[ ✓ ](bg:none fg:purple)'
untracked = '[?\($count\)](bg:none fg:yellow)'
stashed = '[\$](bg:none fg:purple)'
modified = '[!\($count\)](bg:none fg:yellow)'
renamed = '[»\($count\)](bg:none fg:purple)'
deleted = '[✘\($count\)](style)'
staged = '[++\($count\)](bg:none fg:yellow)'
ahead = '[⇡\(${count}\)](bg:none fg:cyan)'
diverged = '⇕[\[](bg:none fg:purple)[⇡\(${ahead_count}\)](bg:none fg:cyan)[⇣\(${behind_count}\)](bg:none fg:pink)[\]](bg:none fg:purple)'
behind = '[⇣\(${count}\)](bg:none fg:pink)'

[time]
disabled = false
# format = " [](fg:overlay)[ $time 󰴈 ]($style)[](fg:overlay)"
format = "  [ $time]($style)"
style = "bg:none fg:yellow"
time_format = "%H:%M"
use_12hr = false

[username]
disabled = false
# format = "[](fg:overlay)[ 󰧱 $user ]($style)[](fg:overlay) "
format = "[$user ]($style)"
show_always = true
style_root = "none fg:purple"
style_user = "bg:none fg:nord_fg"

# Languages

[c]
style = "none fg:aqua"
format = " [](fg:overlay)[ $symbol$version ]($style)[](fg:overlay)"
disabled = false
symbol = " "

[elixir]
style = "none fg:aqua"
format = " [](fg:overlay)[ $symbol$version ]($style)[](fg:overlay)"
disabled = false
symbol = " "

[elm]
style = "none fg:aqua"
format = " [](fg:overlay)[ $symbol$version ]($style)[](fg:overlay)"
disabled = false
symbol = " "

[golang]
style = "none fg:aqua"
format = " [](fg:overlay)[ $symbol$version ]($style)[](fg:overlay)"
disabled = false
symbol = " "

[haskell]
style = "none fg:aqua"
format = " [](fg:overlay)[ $symbol$version ]($style)[](fg:overlay)"
disabled = false
symbol = " "

[java]
style = "none fg:aqua"
format = " [](fg:overlay)[ $symbol$version ]($style)[](fg:overlay)"
disabled = false
symbol = " "

[julia]
style = "none fg:aqua"
format = " [](fg:overlay)[ $symbol$version ]($style)[](fg:overlay)"
disabled = false
symbol = " "

[nodejs]
style = "none fg:aqua"
format = " [](fg:overlay)[ $symbol$version ]($style)[](fg:overlay)"
disabled = false
symbol = "󰎙 "

[nim]
style = "none fg:aqua"
format = " [](fg:overlay)[ $symbol$version ]($style)[](fg:overlay)"
disabled = false
symbol = "󰆥 "

[rust]
style = "none fg:aqua"
format = " [](fg:overlay)[ $symbol$version ]($style)[](fg:overlay)"
disabled = false
symbol = " "

[scala]
style = "none fg:aqua"
format = " [](fg:overlay)[ $symbol$version ]($style)[](fg:overlay)"
disabled = false
symbol = " "

[python]
style = "none fg:aqua"
format = " [](fg:overlay)[ $symbol$version ]($style)[](fg:overlay)"
disabled = false
symbol = ' '

[conda]
style = "none fg:aqua"
format = " [](fg:overlay)[ $symbol$environment ]($style)[](fg:overlay)"
disabled = false
symbol = '🅒 '
