#!/bin/bash

if [ -d ~/.config/nvim ]
then
	rm -rf ~/.config/nvim
	mkdir ~/.config/nvim
fi

cp -r * ~/.config/nvim

# packer (UNIX)
git clone --depth 1 https://github.com/wbthomason/packer.nvim ~/.local/share/nvim/site/pack/packer/start/packer.nvim
